# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0ca951ceae07dab2915c6d5cd6dbf20bc703555b176d7e69b979a21c5cc6e3dd7043c88426c71f2167f85e50200bed61c36a6dbcba194b345bed948678c9af19

test:
  secret_key_base: f244a11a8e0e824d05e05edece5f205f0e9db92dd426abb8fd751164fc5ca407ce7a99d0eb1d275ec1a00a8072a17ac268b971bceed277733fa4e2b4f3ddcf51

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
